import { FreeTextEntryPage } from "./pages/FreeTextEntryPage";
import SearchResult from "./components/SearchResult";
import { TreeStructureSelectPage } from "./pages/TreeStructureSelectPage";
import { Context, createContext } from "react";
import { MainTabsProps, VFCDataContextType, VFCObjectTabsProps, VFCResultsContextType } from "./@types";

export enum VFCType {
	FA = 'FA' as any,
	FO_K = 'FO_K' as any,
	FO_F = 'FO_F' as any,
	FL_F = 'FL_F' as any,
	FL_O = 'FL_O' as any,
	FB = 'FB' as any,
}

export const VFCTypeToID = {
	[VFCType.FA]: "fa",
	[VFCType.FO_F]: "fof",
	[VFCType.FO_K]: "fok",
	[VFCType.FL_F]: "flf",
	[VFCType.FL_O]: "flo",
	[VFCType.FB]: "fb",
} as { [key: string]: string };

export const freeTextSearchTabs: MainTabsProps[] = [
	{
		id: "suchergebnis",
		title: "searchResult",
		component: <SearchResult />,
	},
];
export const mainTabs: MainTabsProps[] = [
	{
		id: "freeTextEntry",
		title: "tabFreeTextEnty",
		component: <FreeTextEntryPage />,
	},
	{
		id: "treeSelection",
		title: "tabTreeView",
		component: <TreeStructureSelectPage />,
	},
];

export const VFCObjectPanels: Array<VFCObjectTabsProps> = [
	{
		id: "fof",
		title: "defectPlace",
		type: VFCType.FO_F,
	},
	{
		id: "fok",
		title: "defectPlace",
		type: VFCType.FO_K,
	},
	{
		id: "fa",
		title: "defectType",
		type: VFCType.FA,
	},
	{
		id: "fe",
		title: "defectLocationVehicle",
		type: VFCType.FL_F,
	},
	{
		id: "fl",
		title: "defectLocationPart",
		type: VFCType.FL_O,
	},
	{
		id: "fb",
		title: "defectCondition",
		type: VFCType.FB,
	},
];

export const VFCDataContext: Context<VFCDataContextType> = createContext<VFCDataContextType>({});
export const VFCResultsContext: Context<VFCResultsContextType> = createContext<VFCResultsContextType>({} as VFCResultsContextType);
export const FPTContext: Context<string> = createContext<string>("K");

const wrongObjects: VFCDataContextType = {
    [VFCType.FA]: [
        {
			vfcId: "555",
			active: true,
			module: "",
			path: "1120202/555",
			descLong: "Invalid values",
			parentVfcId: "1120202",
			selectable: false,
			vfcType: VFCType.FA,
			visualVfcId: "555",
		},
		{
			vfcId: "",
			active: true,
			module: "",
			path: "555/",
			descLong: "No ID",
			parentVfcId: "555",
			selectable: true,
			vfcType: VFCType.FA,
			visualVfcId: "",
		},
		{
			vfcId: "555555555",
			active: true,
			module: "",
			path: "555555555/555",
			descLong: "The one with too long ID FA",
			parentVfcId: "555",
			selectable: true,
			vfcType: VFCType.FA,
			visualVfcId: "555555555",
		},
		{
			vfcId: "555555",
			active: true,
			module: "",
			path: "555/555555",
			descLong: "",
			parentVfcId: "555",
			selectable: true,
			vfcType: VFCType.FA,
			visualVfcId: "555555",
		},
    ],
	[VFCType.FO_F]: [
		{
			vfcId: "666",
			active: true,
			module: "",
			path: "1120202/666",
			descLong: "Invalid values",
			parentVfcId: "1120202",
			selectable: false,
			vfcType: VFCType.FO_F,
			visualVfcId: "666",
		},
		{
			vfcId: "",
			active: true,
			module: "",
			path: "666/",
			descLong: "No ID",
			parentVfcId: "666",
			selectable: true,
			vfcType: VFCType.FO_F,
			visualVfcId: "",
		},
		{
			vfcId: "6666666666",
			active: true,
			module: "",
			path: "666/6666666666",
			descLong: "The one with too long ID FO_F",
			parentVfcId: "666",
			selectable: true,
			vfcType: VFCType.FO_F,
			visualVfcId: "6666666666",
		},
		{
			vfcId: "6666666",
			active: true,
			module: "",
			path: "666/6666666",
			descLong: "",
			parentVfcId: "666",
			selectable: true,
			vfcType: VFCType.FO_F,
			visualVfcId: "6666666",
		},
	],
	[VFCType.FO_K]: [
		{
			vfcId: "333",
			active: true,
			module: "",
			path: "1120202/333",
			descLong: "Invalid values",
			parentVfcId: "1120202",
			selectable: false,
			vfcType: VFCType.FO_K,
			visualVfcId: "333",
		},
		{
			vfcId: "",
			active: true,
			module: "",
			path: "333/",
			descLong: "No ID",
			parentVfcId: "333",
			selectable: true,
			vfcType: VFCType.FO_K,
			visualVfcId: "",
		},
		{
			vfcId: "333333333",
			active: true,
			module: "",
			path: "333/333333333",
			descLong: "The one with too long ID FO_K",
			parentVfcId: "333",
			selectable: true,
			vfcType: VFCType.FO_K,
			visualVfcId: "333333333",
		},
		{
			vfcId: "333333",
			active: true,
			module: "",
			path: "333/333333",
			descLong: "",
			parentVfcId: "333",
			selectable: true,
			vfcType: VFCType.FO_K,
			visualVfcId: "9999999",
		},
	],
	
	[VFCType.FL_F]: [{
        vfcId: "444",
        active: true,
        module: "",
        path: "444",
        descLong: "Invalid values",
        parentVfcId: "1120302",
        selectable: false,
        vfcType: VFCType.FL_F,
        visualVfcId: "444",
    },
    {
        vfcId: "",
        active: true,
        module: "",
        path: "444/",
        descLong: "No ID",
        parentVfcId: "444",
        selectable: true,
        vfcType: VFCType.FL_F,
        visualVfcId: "",
    },
    {
        vfcId: "444444444",
        active: true,
        module: "",
        path: "444/444444444",
        descLong: "The one with too long ID",
        parentVfcId: "444",
        selectable: true,
        vfcType: VFCType.FL_F,
        visualVfcId: "444444444",
    },
    {
        vfcId: "444444",
        active: true,
        module: "",
        path: "444/444444",
        descLong: "",
        parentVfcId: "444",
        selectable: true,
        vfcType: VFCType.FL_F,
        visualVfcId: "444444",
    },],
	[VFCType.FL_O]: [
        {
            vfcId: "222",
            active: true,
            module: "",
            path: "222",
            descLong: "Invalid values",
            parentVfcId: "1120302",
            selectable: false,
            vfcType: VFCType.FL_O,
            visualVfcId: "222",
        },
        {
            vfcId: "",
            active: true,
            module: "",
            path: "222/",
            descLong: "No ID",
            parentVfcId: "222",
            selectable: true,
            vfcType: VFCType.FL_O,
            visualVfcId: "",
        },
        {
            vfcId: "222222222",
            active: true,
            module: "",
            path: "222/222222222",
            descLong: "The one with too long ID",
            parentVfcId: "222",
            selectable: true,
            vfcType: VFCType.FL_O,
            visualVfcId: "222222222",
        },
        {
            vfcId: "222222",
            active: true,
            module: "",
            path: "222/222222",
            descLong: "",
            parentVfcId: "222",
            selectable: true,
            vfcType: VFCType.FL_O,
            visualVfcId: "222222",
        },
    ],
	[VFCType.FB]: [
        {
			vfcId: "777",
			active: true,
			module: "",
			path: "777",
			descLong: "Invalid values",
			parentVfcId: "1120302",
			selectable: false,
			vfcType: VFCType.FB,
			visualVfcId: "777",
		},
		{
			vfcId: "",
			active: true,
			module: "",
			path: "777/",
			descLong: "No ID",
			parentVfcId: "777",
			selectable: true,
			vfcType: VFCType.FB,
			visualVfcId: "",
		},
		{
			vfcId: "777777777",
			active: true,
			module: "",
			path: "777/777777777",
			descLong: "The one with too long ID",
			parentVfcId: "777",
			selectable: true,
			vfcType: VFCType.FB,
			visualVfcId: "777777777",
		},
		{
			vfcId: "777777",
			active: true,
			module: "",
			path: "777/777777",
			descLong: "",
			parentVfcId: "777",
			selectable: true,
			vfcType: VFCType.FB,
			visualVfcId: "777777",
		},
    ],
};

export const getWrongVFCObjects = (type: VFCType) => wrongObjects[type];
